[theme]
# Configuração do tema para melhor visibilidade dos cards
primaryColor = "#2a5298"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans serif"


[server]
# Configurações do servidor
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true


[browser]
# Configurações do navegador
gatherUsageStats = false